# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Gomematic API" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 8080 8090
VOLUME c:\gomematic

ENTRYPOINT ["c:\\gomematic-api.exe"]
CMD ["server"]

ENV GOMEMATIC_API_DB_DSN boltdb:///gomematic/database.db
ENV GOMEMATIC_API_UPLOAD_DSN file:///gomematic/uploads

COPY bin/gomematic-api.exe c:\gomematic-api.exe
